<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="12205" started-at="2019-02-04T18:03:34Z" finished-at="2019-02-04T18:03:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="12205" started-at="2019-02-04T18:03:34Z" finished-at="2019-02-04T18:03:46Z">
      <class name="testCases.PiLoginTest">
        <test-method status="PASS" signature="establishConnection()[pri:0, instance:testCases.PiLoginTest@604ed9f0]" name="establishConnection" is-config="true" duration-ms="12156" started-at="2019-02-04T18:03:34Z" finished-at="2019-02-04T18:03:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- establishConnection -->
        <test-method status="FAIL" signature="piLoginUserNamePassword()[pri:0, instance:testCases.PiLoginTest@604ed9f0]" name="piLoginUserNamePassword" duration-ms="9" started-at="2019-02-04T18:03:46Z" finished-at="2019-02-04T18:03:46Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at testCases.PiLoginTest.piLoginUserNamePassword(PiLoginTest.java:24)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- piLoginUserNamePassword -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testCases.PiLoginTest@604ed9f0]" name="tearDown" is-config="true" duration-ms="0" started-at="2019-02-04T18:03:46Z" finished-at="2019-02-04T18:03:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testCases.PiLoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
